version: "3.8"

services:
  worker:
    init: true
    stop_grace_period: 30s
    stop_signal: SIGTERM
    image: "docker.io/falmar/ec2-docker-swarmkeeper:node${IMAGE_PREFIX}"
    command: [ "worker" ]
    networks:
      - net
      #- host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - source: swarmkeep_env
        target: /app/config.yaml
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 1s
      placement:
        constraints:
          - node.role == worker

  manager:
    init: true
    stop_grace_period: 30s
    stop_signal: SIGTERM
    image: "docker.io/falmar/ec2-docker-swarmkeeper:node${IMAGE_PREFIX}"
    command: [ "manager" ]
    networks:
      - net
      #- host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - source: swarmkeep_env
        target: /app/config.yaml
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 1s
      placement:
        constraints:
          - node.role == manager

secrets:
  swarmkeep_env:
    external: true
    name: swarmkeep_env4
